src/ECS/Asteroid/AsteroidsSystem.cpp
src/ECS/Render/ModelLoading/Material.cpp
src/ECS/Render/ModelLoading/Material.h
src/ECS/Render/ModelLoading/Mesh.cpp
src/ECS/Render/ModelLoading/Mesh.h
src/ECS/Render/ModelLoading/Model.cpp
src/ECS/Render/ModelLoading/Model.h
src/ECS/Render/ModelLoading/Texture.cpp
src/ECS/Render/ModelLoading/Texture.h
src/ECS/Render/Pipelines/PBRPipeline.cpp
src/ECS/Render/Pipelines/PBRPipeline.h
src/ECS/Render/Primitives/Primitives.cpp
src/ECS/Render/Primitives/Primitives.h
src/main.cpp

This commit redesigns the game engine by refactoring the file structure for a logical directory and namespace organization, renaming variables and classes for consistency. It simplifies the texture management through a Material class and enhances shader uniform loading. This cleans up the code, making it easier to manage and read.

Refactor code structure for better organization

---

src/main.cpp

Fix tile draw also fix ui cursor bug

---

src/Mining/IMineable.cpp
src/Unit/UnitAI/StateMachine/States/MovementState.cpp
src/Utils/Time.cpp
src/Utils/Time.h
src/main.cpp

time DeltaTime()  yeeeeeeee  ;-P

Added Time utility class

---

src/Equipment/ConcreteItems/Mop.cpp
src/Equipment/ConcreteItems/Mop.h
src/Equipment/ConcreteItems/WaterGun.cpp
src/Equipment/ConcreteItems/WaterGun.h
src/Equipment/Item.cpp
src/Equipment/Item.h
src/Equipment/UnitEquipment.cpp
src/Equipment/UnitEquipment.h
src/Unit/Unit.cpp
src/Unit/Unit.h

Basic equipment system added

---

src/ECS/Grid/Chunk.cpp
src/ECS/Grid/Chunk.h
src/ECS/Grid/Grid.cpp
src/ECS/HUD/TextRenderer.cpp
src/ECS/Render/InstanceRenderSystem.cpp

Improved the performance and readability of Grid and Renderer code 🎛️. Replaced the 'push_back' usage with 'move' semantics in the Chunk definition for better efficiency ⏩. Also, the wall data management is now accomplished using unique_ptr for better memory handling 🧠. The InstanceRenderSystem has been modified to display the current WallData amount 💡.

Refactor and optimize Grid and Renderer code 🛠️

---

src/ECS/Grid/Grid.cpp
src/ECS/Grid/Grid.h
src/ECS/Grid/Tile.cpp
src/ECS/Grid/Tile.h
src/ECS/Unit/Unit.cpp
src/ECS/Unit/Unit.h
src/ECS/Unit/UnitAI/StateMachine/State.h
src/ECS/Unit/UnitAI/StateMachine/States/CombatState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/CombatState.h
src/ECS/Unit/UnitAI/StateMachine/States/IdleState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/MiningState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/MovementState.cpp
src/main.cpp

POV: You are dirty dirt and a sponge is comin your way

---

src/ECS/Grid/Grid.cpp
src/ECS/Unit/Unit.cpp
src/ECS/Unit/Unit.h
src/ECS/Unit/UnitAI/StateMachine/States/MiningState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/MiningState.h
src/ECS/Utils/AstarPathfinding.cpp
src/main.cpp

as long as mining target is next to floor tile, so that unic can go next to it, its kinda fine. Sometimes its not fine tho and errors fall from the sky. Idk, will fix later. Commit workin 70%, pushing only in case my hardware suddenly collapse into black hole and gets rekt or sth

mining kinda works?

---

src/ECS/Unit/UnitAI/StateMachine/States/MiningState.h

fix missing include

---

src/ECS/Light/Components/DirLight.cpp
src/ECS/Light/Components/PointLight.cpp
src/ECS/Light/Components/SpotLight.cpp
src/main.cpp

Enhanced the spot light shadows setup by introducing additional scoping for shader use and OpenGL commands. 🧹 This aims to improve readability and maintainability of our shadows code. Also, removed unused shader inputs in instance_shadows_depth and instance_point_shadows_depth, leading to more efficient shader execution. 🔍

🔧 Refactored spot light shadows code and shader inputs

---

src/ECS/Entity.h
src/ECS/Grid/Chunk.cpp
src/ECS/Grid/Grid.cpp
src/ECS/Grid/Tile.cpp
src/ECS/Grid/Tile.h
src/ECS/SystemManager.h
src/ECS/Unit/Mining/IMineable.cpp
src/ECS/Unit/Mining/IMineable.h
src/ECS/Unit/Unit.cpp
src/ECS/Unit/Unit.h
src/ECS/Unit/UnitAI/StateMachine/States/CombatState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/IdleState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/MiningState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/MiningState.h
src/ECS/Unit/UnitAI/StateMachine/States/MovementState.cpp
src/ECS/Unit/UnitSystem.cpp
src/ECS/Unit/UnitSystem.h
src/ECS/Utils/AstarPathfinding.cpp
src/ECS/Utils/AstarPathfinding.h
src/main.cpp

Mining stuff

---

src/ECS/Unit/Unit.cpp
src/ECS/Unit/Unit.h
src/ECS/Unit/UnitAI/StateMachine/States/CombatState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/MovementState.cpp
src/main.cpp

ahhh ahh ahhhhh ahhhhh ahh
𒉭𒉭𒉭𒉭𒉭𒉭𒉭𒉭𒉭𒉭𒉭𒉭𒉭𒉭𒉭𒉭𒉭

combat fixes ahhhhhhhhh

---

res/shaders/phongInstance.frag
src/ECS/Grid/Grid.cpp
src/ECS/Grid/Grid.h
src/ECS/Grid/Tile.cpp
src/ECS/Grid/Tile.h
src/main.cpp

A major refactor was done to enhance the visual aspect of the game. The wall's level of dirtiness is now a value that can vary, which is randomly determined and properly visualized on rendering 👁️. This feature makes every wall in the game feel unique. Additionally, some redundant code was removed to make the code cleaner and more readable. The 'init' method now ensures that the random seed is generated based on the current time. This guarantees that every game session is unique.

🔄 Updated shaders and introduced randomness in wall dirtiness 🎲

---

src/ECS/Grid/Tile.cpp
src/ECS/Grid/Tile.h
src/ECS/Unit/Unit.cpp
src/ECS/Unit/Unit.h
src/ECS/Unit/UnitAI/StateMachine/State.h
src/ECS/Unit/UnitAI/StateMachine/States/CombatState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/IdleState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/IdleState.h
src/ECS/Unit/UnitAI/StateMachine/States/MiningState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/MovementState.cpp

Sponges do be cleanin

---

src/ECS/HUD/Group.cpp
src/ECS/HUD/HUD.cpp

Revert "Hud take2" to merge PR #89

---

src/ECS/HUD/Group.cpp
src/ECS/HUD/HUD.cpp

This reverts commit bac1422641440886a920149dca3a14321e887a6e.

Reapply "Hud take2"

---

res/shaders/phong.frag
res/shaders/phongInstance.frag
src/ECS/Render/InstanceRenderSystem.cpp
src/ECS/Render/InstanceRenderSystem.h
src/ECS/Render/RenderSystem.cpp
src/ECS/Render/RenderSystem.h

This commit introduces new uniform variables rim_threshold and rim_amount used to control rim lighting in our shaders. The rim lighting calculation is

🎨 Added rim lighting features to shaders 🎮

---

src/ECS/Unit/Unit.cpp
src/ECS/Unit/UnitAI/StateMachine/States/CombatState.cpp
src/main.cpp

sry nullptr error

---

res/shaders/emmisonInstance.frag
res/shaders/phong.frag
res/shaders/phong.vert
res/shaders/phongInstance.frag
src/ECS/Render/Components/Render.cpp
src/ECS/Render/Components/Render.h
src/ECS/Render/InstanceRenderSystem.cpp
src/ECS/Render/InstanceRenderSystem.h
src/ECS/Render/Pipelines/Phong/PhongPipeline.cpp
src/ECS/Render/Pipelines/Phong/PhongPipeline.h
src/ECS/Render/RenderSystem.cpp
src/main.cpp

Enitity check2

---

src/ECS/Entity.cpp
src/ECS/Render/RenderSystem.cpp
src/ECS/Render/RenderSystem.h
src/ECS/Unit/Mining/MineableChest.cpp
src/ECS/Unit/Unit.cpp
src/ECS/Unit/Unit.h
src/ECS/Unit/UnitAI/StateMachine/States/CombatState.cpp
src/ECS/Unit/UnitAI/UnitAI.cpp
src/main.cpp

fixed some shit, much more to go

---

src/ECS/Grid/Chunk.h
src/ECS/Grid/Grid.cpp
src/ECS/Light/Components/DirLight.cpp
src/ECS/Light/Components/DirLight.h
src/ECS/Light/Components/ILight.h
src/ECS/Light/Components/PointLight.cpp
src/ECS/Light/Components/PointLight.h
src/ECS/Light/Components/SpotLight.cpp
src/ECS/Light/Components/SpotLight.h
src/ECS/Light/LightSystem.cpp
src/ECS/Light/LightSystem.h
src/ECS/Render/Camera/Camera.cpp
src/ECS/Render/Camera/Camera.h
src/ECS/Render/InstanceRenderSystem.cpp
src/main.cpp

This commit involves a major overhaul of the light system handling. Major changes include removal of redundancy in the light system, concentration of light status checks, and optimization of light effect rendering. These changes help streamline the code and improve light system performance at runtime. 😎👌
Added a local light in the grid, streamlining the way light components are managed. This switch has simplified the code and reduced the number of calls made to the_framebuffer_status(). 🌟

📝 Refactored the light system handling 👍

---

src/ECS/LevelGenerator/LevelGenerator.cpp
src/ECS/LevelGenerator/LevelGenerator.h
src/main.cpp

Add item assignment to level generation

---

src/main.cpp

klamra fix

---

src/ECS/Unit/Equipment/Projectile/Projectile.cpp
src/ECS/Unit/Unit.cpp
src/ECS/Unit/UnitAI/StateMachine/States/CombatState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/MiningState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/MovementState.cpp

Gameplay 2.0

---

src/ECS/Unit/Unit.cpp
src/ECS/Unit/UnitAI/StateMachine/States/CombatState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/HealingState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/IdleState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/MiningState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/MovementState.cpp
src/ECS/Utils/AstarPathfinding.cpp

idle anim added

---

res/shaders/spriteRender.frag
res/shaders/spriteRender.vert
src/ECS/Grid/Grid.cpp
src/ECS/Grid/Grid.h
src/ECS/Grid/Tile.cpp
src/ECS/Light/Components/PointLight.cpp
src/ECS/Light/Components/PointLight.h
src/ECS/Render/Components/BetterSpriteRender.cpp
src/ECS/Render/Components/BetterSpriteRender.h
src/ECS/Render/InstanceRenderSystem.cpp
src/ECS/Render/RenderSystem.cpp
src/ECS/Utils/Cursor.cpp
src/main.cpp

Light fix lol

---

src/ECS/Audio/Speaker.cpp
src/ECS/Unit/Unit.cpp
src/ECS/Unit/Unit.h
src/main.cpp

mining fixes

---

src/ECS/HUD/Interactables/HUDSlider.cpp
src/ECS/Unit/Equipment/ConcreteItems/Beacon.cpp
src/ECS/Unit/Equipment/ConcreteItems/Beacon.h
src/ECS/Unit/Equipment/ConcreteItems/WaterGun.h
src/ECS/Unit/Equipment/Item.cpp
src/ECS/Unit/Equipment/Item.h
src/ECS/Unit/Unit.cpp
src/ECS/Unit/UnitAI/StateMachine/States/CombatState.cpp
src/ECS/Unit/UnitAI/StateMachine/States/CombatState.h
src/ECS/Utils/Util.cpp

Healing beacon fixes

---

src/ECS/LevelGenerator/LevelGenerator.cpp
src/ECS/LevelGenerator/LevelGenerator.h
src/main.cpp

Abolish segregation of enemy types

---

src/ECS/Grid/Grid.cpp

quick fix for broken wieszak

---

src/ECS/Render/Camera/Camera.cpp
src/ECS/Render/Camera/Camera.h
src/main.cpp

Camera rotation

---

src/ECS/Unit/Unit.cpp
src/ECS/Unit/UnitAI/StateMachine/States/CombatState.cpp

enemy search range increase

---

README.md
site/README.md

Updated README files to include a comprehensive list of major features implemented in the project. This enhances documentation clarity and provides an overview of the project's core systems and functionalities.

Add feature list to documentation
